package com.demo.dao;

import com.demo.model.EnfordProductOrganization;

import java.util.List;

public interface EnfordProductOrganizationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enford_product_organization
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enford_product_organization
     *
     * @mbggenerated
     */
    int insert(EnfordProductOrganization record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enford_product_organization
     *
     * @mbggenerated
     */
    int insertSelective(EnfordProductOrganization record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enford_product_organization
     *
     * @mbggenerated
     */
    EnfordProductOrganization selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enford_product_organization
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(EnfordProductOrganization record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enford_product_organization
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(EnfordProductOrganization record);

    List<EnfordProductOrganization> select();
}