package com.demo.dao;

import com.demo.model.EnfordProductImportHistory;

import java.util.List;

public interface EnfordProductImportHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enford_product_import_history
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enford_product_import_history
     *
     * @mbggenerated
     */
    int insert(EnfordProductImportHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enford_product_import_history
     *
     * @mbggenerated
     */
    int insertSelective(EnfordProductImportHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enford_product_import_history
     *
     * @mbggenerated
     */
    EnfordProductImportHistory selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enford_product_import_history
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(EnfordProductImportHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enford_product_import_history
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(EnfordProductImportHistory record);

    List<EnfordProductImportHistory> selectByType(int type);
}