package com.demo.dao;

import com.demo.model.EnfordMarketLocation;

import java.util.List;
import java.util.Map;

public interface EnfordMarketLocationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enford_market_location
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enford_market_location
     *
     * @mbggenerated
     */
    int insert(EnfordMarketLocation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enford_market_location
     *
     * @mbggenerated
     */
    int insertSelective(EnfordMarketLocation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enford_market_location
     *
     * @mbggenerated
     */
    EnfordMarketLocation selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enford_market_location
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(EnfordMarketLocation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enford_market_location
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(EnfordMarketLocation record);

    int countLocation(Map<String, Object> param);

    List<EnfordMarketLocation> selectLocationByParam(Map<String, Object> param);
}