package com.demo.dao;

import com.demo.model.EnfordProductCompetitors;

import java.util.List;
import java.util.Map;

public interface EnfordProductCompetitorsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enford_product_competitors
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enford_product_competitors
     *
     * @mbggenerated
     */
    int insert(EnfordProductCompetitors record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enford_product_competitors
     *
     * @mbggenerated
     */
    int insertSelective(EnfordProductCompetitors record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enford_product_competitors
     *
     * @mbggenerated
     */
    EnfordProductCompetitors selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enford_product_competitors
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(EnfordProductCompetitors record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enford_product_competitors
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(EnfordProductCompetitors record);

    List<EnfordProductCompetitors> selectByParam(Map<String, Object> param);

    int maxId();

    List<EnfordProductCompetitors> select();
}