package com.demo.dao;

import com.demo.model.EnfordSyncLog;

public interface EnfordSyncLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enford_sync_log
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enford_sync_log
     *
     * @mbggenerated
     */
    int insert(EnfordSyncLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enford_sync_log
     *
     * @mbggenerated
     */
    int insertSelective(EnfordSyncLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enford_sync_log
     *
     * @mbggenerated
     */
    EnfordSyncLog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enford_sync_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(EnfordSyncLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enford_sync_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(EnfordSyncLog record);
}