package com.demo.dao;

import com.demo.model.EnfordCustomProduct;
import com.demo.model.EnfordCustomProductKey;

public interface EnfordCustomProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enford_custom_product
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(EnfordCustomProductKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enford_custom_product
     *
     * @mbggenerated
     */
    int insert(EnfordCustomProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enford_custom_product
     *
     * @mbggenerated
     */
    int insertSelective(EnfordCustomProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enford_custom_product
     *
     * @mbggenerated
     */
    EnfordCustomProduct selectByPrimaryKey(EnfordCustomProductKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enford_custom_product
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(EnfordCustomProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enford_custom_product
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(EnfordCustomProduct record);
}