package com.demo.dao;

import com.demo.model.EnfordProductPrice;

public interface EnfordProductPriceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enford_product_price
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enford_product_price
     *
     * @mbggenerated
     */
    int insert(EnfordProductPrice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enford_product_price
     *
     * @mbggenerated
     */
    int insertSelective(EnfordProductPrice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enford_product_price
     *
     * @mbggenerated
     */
    EnfordProductPrice selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enford_product_price
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(EnfordProductPrice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enford_product_price
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(EnfordProductPrice record);
}