package com.demo.dao;

import com.demo.model.EnfordProductCommodity;

public interface EnfordProductCommodityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enford_product_commodity
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enford_product_commodity
     *
     * @mbggenerated
     */
    int insert(EnfordProductCommodity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enford_product_commodity
     *
     * @mbggenerated
     */
    int insertSelective(EnfordProductCommodity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enford_product_commodity
     *
     * @mbggenerated
     */
    EnfordProductCommodity selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enford_product_commodity
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(EnfordProductCommodity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enford_product_commodity
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(EnfordProductCommodity record);
}