package com.demo.dao;

import com.demo.model.EnfordProductCity;

import java.util.List;
import java.util.Map;

public interface EnfordProductCityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enford_product_city
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enford_product_city
     *
     * @mbggenerated
     */
    int insert(EnfordProductCity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enford_product_city
     *
     * @mbggenerated
     */
    int insertSelective(EnfordProductCity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enford_product_city
     *
     * @mbggenerated
     */
    EnfordProductCity selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enford_product_city
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(EnfordProductCity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enford_product_city
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(EnfordProductCity record);

    List<EnfordProductCity> selectByParam(Map<String, Object> param);

    Integer maxId();
}