package com.demo.dao;

import com.demo.model.EnfordProduct;

public interface EnfordProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enford_product
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enford_product
     *
     * @mbggenerated
     */
    int insert(EnfordProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enford_product
     *
     * @mbggenerated
     */
    int insertSelective(EnfordProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enford_product
     *
     * @mbggenerated
     */
    EnfordProduct selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enford_product
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(EnfordProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enford_product
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(EnfordProduct record);
}