package com.demo.dao;

import com.demo.model.EnfordUser;

import java.util.Map;

public interface EnfordUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enford_user
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enford_user
     *
     * @mbggenerated
     */
    int insert(EnfordUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enford_user
     *
     * @mbggenerated
     */
    int insertSelective(EnfordUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enford_user
     *
     * @mbggenerated
     */
    EnfordUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enford_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(EnfordUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enford_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(EnfordUser record);

    EnfordUser selectByParam(Map<String, Object> param);
}