package com.demo.dao;

import com.demo.model.EnfordMarketResearchCommodity;

public interface EnfordMarketResearchCommodityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enford_market_research_commodity
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enford_market_research_commodity
     *
     * @mbggenerated
     */
    int insert(EnfordMarketResearchCommodity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enford_market_research_commodity
     *
     * @mbggenerated
     */
    int insertSelective(EnfordMarketResearchCommodity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enford_market_research_commodity
     *
     * @mbggenerated
     */
    EnfordMarketResearchCommodity selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enford_market_research_commodity
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(EnfordMarketResearchCommodity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enford_market_research_commodity
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(EnfordMarketResearchCommodity record);
}