package com.demo.dao;

import com.demo.model.EnfordProductSupplier;

import java.util.List;

public interface EnfordProductSupplierMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enford_product_supplier
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enford_product_supplier
     *
     * @mbggenerated
     */
    int insert(EnfordProductSupplier record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enford_product_supplier
     *
     * @mbggenerated
     */
    int insertSelective(EnfordProductSupplier record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enford_product_supplier
     *
     * @mbggenerated
     */
    EnfordProductSupplier selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enford_product_supplier
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(EnfordProductSupplier record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enford_product_supplier
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(EnfordProductSupplier record);

    EnfordProductSupplier selectByCode(String code);

    List<EnfordProductSupplier> select();
}