package com.demo.dao;

import com.demo.model.EnfordCustom;

public interface EnfordCustomMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enford_custom
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enford_custom
     *
     * @mbggenerated
     */
    int insert(EnfordCustom record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enford_custom
     *
     * @mbggenerated
     */
    int insertSelective(EnfordCustom record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enford_custom
     *
     * @mbggenerated
     */
    EnfordCustom selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enford_custom
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(EnfordCustom record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enford_custom
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(EnfordCustom record);
}