package com.demo.dao;

import com.demo.model.EnfordProductDepartment;

import java.util.List;
import java.util.Map;

public interface EnfordProductDepartmentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enford_product_department
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enford_product_department
     *
     * @mbggenerated
     */
    int insert(EnfordProductDepartment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enford_product_department
     *
     * @mbggenerated
     */
    int insertSelective(EnfordProductDepartment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enford_product_department
     *
     * @mbggenerated
     */
    EnfordProductDepartment selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enford_product_department
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(EnfordProductDepartment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enford_product_department
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(EnfordProductDepartment record);

    List<EnfordProductDepartment> selectByParam(Map<String, Object> param);

    List<EnfordProductDepartment> selectAll();

    List<EnfordProductDepartment> selectByResId(Map<String, Object> param);

    List<EnfordProductDepartment> selectByAreaName(Map<String, Object> param);

    int countByParam(Map<String, Object> param);

    List<EnfordProductDepartment> selectNotInArea(Map<String, Object> param);
}