package com.demo.dao;

import com.demo.model.EnfordSystemLog;

public interface EnfordSystemLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enford_system_log
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enford_system_log
     *
     * @mbggenerated
     */
    int insert(EnfordSystemLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enford_system_log
     *
     * @mbggenerated
     */
    int insertSelective(EnfordSystemLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enford_system_log
     *
     * @mbggenerated
     */
    EnfordSystemLog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enford_system_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(EnfordSystemLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enford_system_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(EnfordSystemLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enford_system_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(EnfordSystemLog record);
}