package com.demo.dao;

import com.demo.model.EnfordMarketResearchDept;
import com.demo.model.EnfordMarketResearchDeptKey;

import java.util.List;
import java.util.Map;

public interface EnfordMarketResearchDeptMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enford_market_research_dept
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(EnfordMarketResearchDeptKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enford_market_research_dept
     *
     * @mbggenerated
     */
    int insert(EnfordMarketResearchDept record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enford_market_research_dept
     *
     * @mbggenerated
     */
    int insertSelective(EnfordMarketResearchDept record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enford_market_research_dept
     *
     * @mbggenerated
     */
    EnfordMarketResearchDept selectByPrimaryKey(EnfordMarketResearchDeptKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enford_market_research_dept
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(EnfordMarketResearchDept record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enford_market_research_dept
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(EnfordMarketResearchDept record);

    List<EnfordMarketResearchDept> selectByParam(Map<String, Object> param);

    int countByParam(Map<String, Object> param);
}