package com.demo.dao;

import com.demo.model.EnfordProductCommodity;
import org.apache.ibatis.annotations.Param;

import java.util.List;
import java.util.Map;

public interface EnfordProductCommodityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enford_product_commodity
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enford_product_commodity
     *
     * @mbggenerated
     */
    int insert(EnfordProductCommodity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enford_product_commodity
     *
     * @mbggenerated
     */
    int insertSelective(EnfordProductCommodity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enford_product_commodity
     *
     * @mbggenerated
     */
    EnfordProductCommodity selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enford_product_commodity
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(EnfordProductCommodity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enford_product_commodity
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(EnfordProductCommodity record);

    int maxId();

    List<EnfordProductCommodity> selectByParam(Map<String, Object> param);

    List<EnfordProductCommodity> select();
}