package com.demo.dao;

import com.demo.model.EnfordMarketResearch;

import java.util.List;
import java.util.Map;

public interface EnfordMarketResearchMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enford_market_research
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enford_market_research
     *
     * @mbggenerated
     */
    int insert(EnfordMarketResearch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enford_market_research
     *
     * @mbggenerated
     */
    int insertSelective(EnfordMarketResearch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enford_market_research
     *
     * @mbggenerated
     */
    EnfordMarketResearch selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enford_market_research
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(EnfordMarketResearch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enford_market_research
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(EnfordMarketResearch record);

    EnfordMarketResearch selectByImportId(Integer importId);

    List<EnfordMarketResearch> selectByParam(Map<String, Object> param);

    int countByParam(Map<String, Object> param);
}