package com.demo.dao;

import com.demo.model.EnfordProductPrice;
import com.demo.model.EnfordProductPriceKey;

import java.util.List;
import java.util.Map;

public interface EnfordProductPriceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enford_product_price
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(EnfordProductPriceKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enford_product_price
     *
     * @mbggenerated
     */
    int insert(EnfordProductPrice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enford_product_price
     *
     * @mbggenerated
     */
    int insertSelective(EnfordProductPrice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enford_product_price
     *
     * @mbggenerated
     */
    EnfordProductPrice selectByPrimaryKey(EnfordProductPriceKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enford_product_price
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(EnfordProductPrice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enford_product_price
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(EnfordProductPrice record);

    List<EnfordProductPrice> selectByParam(Map<String, Object> param);


    int countByParam(Map<String, Object> param);
}