package com.demo.dao;

import com.demo.model.EnfordSystemRole;

import java.util.List;

public interface EnfordSystemRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enford_system_role
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enford_system_role
     *
     * @mbggenerated
     */
    int insert(EnfordSystemRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enford_system_role
     *
     * @mbggenerated
     */
    int insertSelective(EnfordSystemRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enford_system_role
     *
     * @mbggenerated
     */
    EnfordSystemRole selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enford_system_role
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(EnfordSystemRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enford_system_role
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(EnfordSystemRole record);

    List<EnfordSystemRole> select();

    int max();
}