package com.demo.model;

public class EnfordMarketResearchCommodity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enford_market_research_commodity.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enford_market_research_commodity.res_id
     *
     * @mbggenerated
     */
    private Integer resId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enford_market_research_commodity.cod_id
     *
     * @mbggenerated
     */
    private Integer codId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enford_market_research_commodity.id
     *
     * @return the value of enford_market_research_commodity.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enford_market_research_commodity.id
     *
     * @param id the value for enford_market_research_commodity.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enford_market_research_commodity.res_id
     *
     * @return the value of enford_market_research_commodity.res_id
     *
     * @mbggenerated
     */
    public Integer getResId() {
        return resId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enford_market_research_commodity.res_id
     *
     * @param resId the value for enford_market_research_commodity.res_id
     *
     * @mbggenerated
     */
    public void setResId(Integer resId) {
        this.resId = resId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enford_market_research_commodity.cod_id
     *
     * @return the value of enford_market_research_commodity.cod_id
     *
     * @mbggenerated
     */
    public Integer getCodId() {
        return codId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enford_market_research_commodity.cod_id
     *
     * @param codId the value for enford_market_research_commodity.cod_id
     *
     * @mbggenerated
     */
    public void setCodId(Integer codId) {
        this.codId = codId;
    }
}