package com.demo.model;

import java.util.List;

public class EnfordProductArea {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enford_product_area.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enford_product_area.name
     *
     * @mbggenerated
     */
    private String name;

    private List<EnfordProductDepartment> children;

    private int countByMonth;

    private int countByYear;

    private String finishPercentByMonth;

    private String finishPercentByYear;

    private String cci;

    private String cost;

    private String finishByYear;

    private String notFinishByYear;

    private String codCountByYear;

    private String finishByMonth;

    private String notFinishByMonth;

    private String codCountByMonth;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enford_product_area.id
     *
     * @return the value of enford_product_area.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enford_product_area.id
     *
     * @param id the value for enford_product_area.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enford_product_area.name
     *
     * @return the value of enford_product_area.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enford_product_area.name
     *
     * @param name the value for enford_product_area.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    public List<EnfordProductDepartment> getChildren() {
        return children;
    }

    public void setChildren(List<EnfordProductDepartment> children) {
        this.children = children;
    }

    public int getCountByMonth() {
        return countByMonth;
    }

    public void setCountByMonth(int countByMonth) {
        this.countByMonth = countByMonth;
    }

    public int getCountByYear() {
        return countByYear;
    }

    public void setCountByYear(int countByYear) {
        this.countByYear = countByYear;
    }

    public String getFinishPercentByMonth() {
        return finishPercentByMonth;
    }

    public void setFinishPercentByMonth(String finishPercentByMonth) {
        this.finishPercentByMonth = finishPercentByMonth;
    }

    public String getFinishPercentByYear() {
        return finishPercentByYear;
    }

    public void setFinishPercentByYear(String finishPercentByYear) {
        this.finishPercentByYear = finishPercentByYear;
    }

    public String getCci() {
        return cci;
    }

    public void setCci(String cci) {
        this.cci = cci;
    }

    public String getCost() {
        return cost;
    }

    public void setCost(String cost) {
        this.cost = cost;
    }

    public String getFinishByYear() {
        return finishByYear;
    }

    public void setFinishByYear(String finishByYear) {
        this.finishByYear = finishByYear;
    }

    public String getNotFinishByYear() {
        return notFinishByYear;
    }

    public void setNotFinishByYear(String notFinishByYear) {
        this.notFinishByYear = notFinishByYear;
    }

    public String getCodCountByYear() {
        return codCountByYear;
    }

    public void setCodCountByYear(String codCountByYear) {
        this.codCountByYear = codCountByYear;
    }

    public String getFinishByMonth() {
        return finishByMonth;
    }

    public void setFinishByMonth(String finishByMonth) {
        this.finishByMonth = finishByMonth;
    }

    public String getNotFinishByMonth() {
        return notFinishByMonth;
    }

    public void setNotFinishByMonth(String notFinishByMonth) {
        this.notFinishByMonth = notFinishByMonth;
    }

    public String getCodCountByMonth() {
        return codCountByMonth;
    }

    public void setCodCountByMonth(String codCountByMonth) {
        this.codCountByMonth = codCountByMonth;
    }
}