package com.demo.model;

import java.util.List;

public class EnfordProductCity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enford_product_city.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enford_product_city.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enford_product_city.province
     *
     * @mbggenerated
     */
    private String province;

    private List<EnfordProductDepartment> children;
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enford_product_city.id
     *
     * @return the value of enford_product_city.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enford_product_city.id
     *
     * @param id the value for enford_product_city.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enford_product_city.name
     *
     * @return the value of enford_product_city.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enford_product_city.name
     *
     * @param name the value for enford_product_city.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enford_product_city.province
     *
     * @return the value of enford_product_city.province
     *
     * @mbggenerated
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enford_product_city.province
     *
     * @param province the value for enford_product_city.province
     *
     * @mbggenerated
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    public List<EnfordProductDepartment> getChildren() {
        return children;
    }

    public void setChildren(List<EnfordProductDepartment> children) {
        this.children = children;
    }
}