package com.demo.model;

import com.alibaba.fastjson.annotation.JSONField;

import java.util.Date;

public class EnfordProductCommodity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enford_product_commodity.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enford_product_commodity.code
     *
     * @mbggenerated
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enford_product_commodity.art_no
     *
     * @mbggenerated
     */
    private String artNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enford_product_commodity.p_name
     *
     * @mbggenerated
     */
    private String pName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enford_product_commodity.p_size
     *
     * @mbggenerated
     */
    private String pSize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enford_product_commodity.unit
     *
     * @mbggenerated
     */
    private String unit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enford_product_commodity.bar_code
     *
     * @mbggenerated
     */
    private String barCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enford_product_commodity.supplier_code
     *
     * @mbggenerated
     */
    private String supplierCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enford_product_commodity.category_code
     *
     * @mbggenerated
     */
    private Integer categoryCode;

    private String categoryName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enford_product_commodity.create_dt
     *
     * @mbggenerated
     */
    @JSONField(format="yyyy-MM-dd HH:mm:ss")
    private Date createDt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enford_product_commodity.update_dt
     *
     * @mbggenerated
     */
    @JSONField (format="yyyy-MM-dd HH:mm:ss")
    private Date updateDt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enford_product_commodity.create_by
     *
     * @mbggenerated
     */
    private Integer createBy;

    private String createUsername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enford_product_commodity.update_by
     *
     * @mbggenerated
     */
    private Integer updateBy;

    private EnfordProductPrice price;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enford_product_commodity.id
     *
     * @return the value of enford_product_commodity.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enford_product_commodity.id
     *
     * @param id the value for enford_product_commodity.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enford_product_commodity.code
     *
     * @return the value of enford_product_commodity.code
     *
     * @mbggenerated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enford_product_commodity.code
     *
     * @param code the value for enford_product_commodity.code
     *
     * @mbggenerated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enford_product_commodity.art_no
     *
     * @return the value of enford_product_commodity.art_no
     *
     * @mbggenerated
     */
    public String getArtNo() {
        return artNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enford_product_commodity.art_no
     *
     * @param artNo the value for enford_product_commodity.art_no
     *
     * @mbggenerated
     */
    public void setArtNo(String artNo) {
        this.artNo = artNo == null ? null : artNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enford_product_commodity.p_name
     *
     * @return the value of enford_product_commodity.p_name
     *
     * @mbggenerated
     */
    public String getpName() {
        return pName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enford_product_commodity.p_name
     *
     * @param pName the value for enford_product_commodity.p_name
     *
     * @mbggenerated
     */
    public void setpName(String pName) {
        this.pName = pName == null ? null : pName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enford_product_commodity.p_size
     *
     * @return the value of enford_product_commodity.p_size
     *
     * @mbggenerated
     */
    public String getpSize() {
        return pSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enford_product_commodity.p_size
     *
     * @param pSize the value for enford_product_commodity.p_size
     *
     * @mbggenerated
     */
    public void setpSize(String pSize) {
        this.pSize = pSize == null ? null : pSize.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enford_product_commodity.unit
     *
     * @return the value of enford_product_commodity.unit
     *
     * @mbggenerated
     */
    public String getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enford_product_commodity.unit
     *
     * @param unit the value for enford_product_commodity.unit
     *
     * @mbggenerated
     */
    public void setUnit(String unit) {
        this.unit = unit == null ? null : unit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enford_product_commodity.bar_code
     *
     * @return the value of enford_product_commodity.bar_code
     *
     * @mbggenerated
     */
    public String getBarCode() {
        return barCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enford_product_commodity.bar_code
     *
     * @param barCode the value for enford_product_commodity.bar_code
     *
     * @mbggenerated
     */
    public void setBarCode(String barCode) {
        this.barCode = barCode == null ? null : barCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enford_product_commodity.supplier_code
     *
     * @return the value of enford_product_commodity.supplier_code
     *
     * @mbggenerated
     */
    public String getSupplierCode() {
        return supplierCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enford_product_commodity.supplier_code
     *
     * @param supplierCode the value for enford_product_commodity.supplier_code
     *
     * @mbggenerated
     */
    public void setSupplierCode(String supplierCode) {
        this.supplierCode = supplierCode == null ? null : supplierCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enford_product_commodity.category_code
     *
     * @return the value of enford_product_commodity.category_code
     *
     * @mbggenerated
     */
    public Integer getCategoryCode() {
        return categoryCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enford_product_commodity.category_code
     *
     * @param categoryCode the value for enford_product_commodity.category_code
     *
     * @mbggenerated
     */
    public void setCategoryCode(Integer categoryCode) {
        this.categoryCode = categoryCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enford_product_commodity.create_dt
     *
     * @return the value of enford_product_commodity.create_dt
     *
     * @mbggenerated
     */
    public Date getCreateDt() {
        return createDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enford_product_commodity.create_dt
     *
     * @param createDt the value for enford_product_commodity.create_dt
     *
     * @mbggenerated
     */
    public void setCreateDt(Date createDt) {
        this.createDt = createDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enford_product_commodity.update_dt
     *
     * @return the value of enford_product_commodity.update_dt
     *
     * @mbggenerated
     */
    public Date getUpdateDt() {
        return updateDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enford_product_commodity.update_dt
     *
     * @param updateDt the value for enford_product_commodity.update_dt
     *
     * @mbggenerated
     */
    public void setUpdateDt(Date updateDt) {
        this.updateDt = updateDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enford_product_commodity.create_by
     *
     * @return the value of enford_product_commodity.create_by
     *
     * @mbggenerated
     */
    public Integer getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enford_product_commodity.create_by
     *
     * @param createBy the value for enford_product_commodity.create_by
     *
     * @mbggenerated
     */
    public void setCreateBy(Integer createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enford_product_commodity.update_by
     *
     * @return the value of enford_product_commodity.update_by
     *
     * @mbggenerated
     */
    public Integer getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enford_product_commodity.update_by
     *
     * @param updateBy the value for enford_product_commodity.update_by
     *
     * @mbggenerated
     */
    public void setUpdateBy(Integer updateBy) {
        this.updateBy = updateBy;
    }

    public String getCategoryName() {
        return categoryName;
    }

    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName;
    }

    public String getCreateUsername() {
        return createUsername;
    }

    public void setCreateUsername(String createUsername) {
        this.createUsername = createUsername;
    }

    public EnfordProductPrice getPrice() {
        return price;
    }

    public void setPrice(EnfordProductPrice price) {
        this.price = price;
    }

    @Override
    public String toString() {
        return "EnfordProductCommodity{" +
                "id=" + id +
                ", code='" + code + '\'' +
                ", artNo='" + artNo + '\'' +
                ", pName='" + pName + '\'' +
                ", pSize='" + pSize + '\'' +
                ", unit='" + unit + '\'' +
                ", barCode='" + barCode + '\'' +
                ", supplierCode='" + supplierCode + '\'' +
                ", categoryCode=" + categoryCode +
                ", categoryName='" + categoryName + '\'' +
                ", createDt=" + createDt +
                ", updateDt=" + updateDt +
                ", createBy=" + createBy +
                ", createUsername='" + createUsername + '\'' +
                ", updateBy=" + updateBy +
                ", price=" + price +
                '}';
    }
}