package com.demo.model;

public class EnfordSystemRoleMenu {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enford_system_role_menu.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enford_system_role_menu.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enford_system_role_menu.role_id
     *
     * @mbggenerated
     */
    private Integer roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enford_system_role_menu.menu_id
     *
     * @mbggenerated
     */
    private Integer menuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enford_system_role_menu.action
     *
     * @mbggenerated
     */
    private Integer action;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enford_system_role_menu.id
     *
     * @return the value of enford_system_role_menu.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enford_system_role_menu.id
     *
     * @param id the value for enford_system_role_menu.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enford_system_role_menu.name
     *
     * @return the value of enford_system_role_menu.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enford_system_role_menu.name
     *
     * @param name the value for enford_system_role_menu.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enford_system_role_menu.role_id
     *
     * @return the value of enford_system_role_menu.role_id
     *
     * @mbggenerated
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enford_system_role_menu.role_id
     *
     * @param roleId the value for enford_system_role_menu.role_id
     *
     * @mbggenerated
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enford_system_role_menu.menu_id
     *
     * @return the value of enford_system_role_menu.menu_id
     *
     * @mbggenerated
     */
    public Integer getMenuId() {
        return menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enford_system_role_menu.menu_id
     *
     * @param menuId the value for enford_system_role_menu.menu_id
     *
     * @mbggenerated
     */
    public void setMenuId(Integer menuId) {
        this.menuId = menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enford_system_role_menu.action
     *
     * @return the value of enford_system_role_menu.action
     *
     * @mbggenerated
     */
    public Integer getAction() {
        return action;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enford_system_role_menu.action
     *
     * @param action the value for enford_system_role_menu.action
     *
     * @mbggenerated
     */
    public void setAction(Integer action) {
        this.action = action;
    }
}