package com.demo.model;

public class EnfordProductPriceKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enford_product_price.import_id
     *
     * @mbggenerated
     */
    private Integer importId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enford_product_price.org_id
     *
     * @mbggenerated
     */
    private Integer orgId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enford_product_price.com_id
     *
     * @mbggenerated
     */
    private Integer comId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enford_product_price.import_id
     *
     * @return the value of enford_product_price.import_id
     *
     * @mbggenerated
     */
    public Integer getImportId() {
        return importId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enford_product_price.import_id
     *
     * @param importId the value for enford_product_price.import_id
     *
     * @mbggenerated
     */
    public void setImportId(Integer importId) {
        this.importId = importId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enford_product_price.org_id
     *
     * @return the value of enford_product_price.org_id
     *
     * @mbggenerated
     */
    public Integer getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enford_product_price.org_id
     *
     * @param orgId the value for enford_product_price.org_id
     *
     * @mbggenerated
     */
    public void setOrgId(Integer orgId) {
        this.orgId = orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enford_product_price.com_id
     *
     * @return the value of enford_product_price.com_id
     *
     * @mbggenerated
     */
    public Integer getComId() {
        return comId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enford_product_price.com_id
     *
     * @param comId the value for enford_product_price.com_id
     *
     * @mbggenerated
     */
    public void setComId(Integer comId) {
        this.comId = comId;
    }
}