package com.demo.model;

import com.alibaba.fastjson.annotation.JSONField;

import java.util.Date;

public class EnfordMarketResearch {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enford_market_research.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enford_market_research.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enford_market_research.create_by
     *
     * @mbggenerated
     */
    private Integer createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enford_market_research.create_dt
     *
     * @mbggenerated
     */
    @JSONField (format="yyyy-MM-dd HH:mm:ss")
    private Date createDt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enford_market_research.start_dt
     *
     * @mbggenerated
     */
    @JSONField(format="yyyy-MM-dd HH:mm:ss")
    private Date startDt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enford_market_research.end_dt
     *
     * @mbggenerated
     */
    private Date endDt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enford_market_research.exe_store_id
     *
     * @mbggenerated
     */
    private Integer exeStoreId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enford_market_research.res_store_id
     *
     * @mbggenerated
     */
    private Integer resStoreId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enford_market_research.import_id
     *
     * @mbggenerated
     */
    private Integer importId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enford_market_research.id
     *
     * @return the value of enford_market_research.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enford_market_research.id
     *
     * @param id the value for enford_market_research.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enford_market_research.name
     *
     * @return the value of enford_market_research.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enford_market_research.name
     *
     * @param name the value for enford_market_research.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enford_market_research.create_by
     *
     * @return the value of enford_market_research.create_by
     *
     * @mbggenerated
     */
    public Integer getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enford_market_research.create_by
     *
     * @param createBy the value for enford_market_research.create_by
     *
     * @mbggenerated
     */
    public void setCreateBy(Integer createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enford_market_research.create_dt
     *
     * @return the value of enford_market_research.create_dt
     *
     * @mbggenerated
     */
    public Date getCreateDt() {
        return createDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enford_market_research.create_dt
     *
     * @param createDt the value for enford_market_research.create_dt
     *
     * @mbggenerated
     */
    public void setCreateDt(Date createDt) {
        this.createDt = createDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enford_market_research.start_dt
     *
     * @return the value of enford_market_research.start_dt
     *
     * @mbggenerated
     */
    public Date getStartDt() {
        return startDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enford_market_research.start_dt
     *
     * @param startDt the value for enford_market_research.start_dt
     *
     * @mbggenerated
     */
    public void setStartDt(Date startDt) {
        this.startDt = startDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enford_market_research.end_dt
     *
     * @return the value of enford_market_research.end_dt
     *
     * @mbggenerated
     */
    public Date getEndDt() {
        return endDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enford_market_research.end_dt
     *
     * @param endDt the value for enford_market_research.end_dt
     *
     * @mbggenerated
     */
    public void setEndDt(Date endDt) {
        this.endDt = endDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enford_market_research.exe_store_id
     *
     * @return the value of enford_market_research.exe_store_id
     *
     * @mbggenerated
     */
    public Integer getExeStoreId() {
        return exeStoreId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enford_market_research.exe_store_id
     *
     * @param exeStoreId the value for enford_market_research.exe_store_id
     *
     * @mbggenerated
     */
    public void setExeStoreId(Integer exeStoreId) {
        this.exeStoreId = exeStoreId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enford_market_research.res_store_id
     *
     * @return the value of enford_market_research.res_store_id
     *
     * @mbggenerated
     */
    public Integer getResStoreId() {
        return resStoreId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enford_market_research.res_store_id
     *
     * @param resStoreId the value for enford_market_research.res_store_id
     *
     * @mbggenerated
     */
    public void setResStoreId(Integer resStoreId) {
        this.resStoreId = resStoreId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enford_market_research.import_id
     *
     * @return the value of enford_market_research.import_id
     *
     * @mbggenerated
     */
    public Integer getImportId() {
        return importId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enford_market_research.import_id
     *
     * @param importId the value for enford_market_research.import_id
     *
     * @mbggenerated
     */
    public void setImportId(Integer importId) {
        this.importId = importId;
    }
}