package com.demo.model;

import java.util.List;

public class EnfordProductCompetitors {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enford_product_competitors.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enford_product_competitors.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enford_product_competitors.city_id
     *
     * @mbggenerated
     */
    private Integer cityId;

    private String cityName;

    private List<EnfordProductDepartment> children;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enford_product_competitors.id
     *
     * @return the value of enford_product_competitors.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enford_product_competitors.id
     *
     * @param id the value for enford_product_competitors.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enford_product_competitors.name
     *
     * @return the value of enford_product_competitors.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enford_product_competitors.name
     *
     * @param name the value for enford_product_competitors.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enford_product_competitors.city_id
     *
     * @return the value of enford_product_competitors.city_id
     *
     * @mbggenerated
     */
    public Integer getCityId() {
        return cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enford_product_competitors.city_id
     *
     * @param cityId the value for enford_product_competitors.city_id
     *
     * @mbggenerated
     */
    public void setCityId(Integer cityId) {
        this.cityId = cityId;
    }

    public String getCityName() {
        return cityName;
    }

    public void setCityName(String cityName) {
        this.cityName = cityName;
    }

    public List<EnfordProductDepartment> getChildren() {
        return children;
    }

    public void setChildren(List<EnfordProductDepartment> children) {
        this.children = children;
    }
}