package com.demo.model;

import com.alibaba.fastjson.annotation.JSONField;

import java.util.Date;

public class EnfordProductImportHistory {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enford_product_import_history.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enford_product_import_history.file_name
     *
     * @mbggenerated
     */
    private String fileName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enford_product_import_history.size
     *
     * @mbggenerated
     */
    private String size;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enford_product_import_history.create_by
     *
     * @mbggenerated
     */
    private Integer createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enford_product_import_history.create_dt
     *
     * @mbggenerated
     */
    @JSONField(format="yyyy-MM-dd HH:mm:ss")
    private Date createDt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enford_product_import_history.state
     *
     * @mbggenerated
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enford_product_import_history.file_path
     *
     * @mbggenerated
     */
    private String filePath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enford_product_import_history.file_type
     *
     * @mbggenerated
     */
    private String fileType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enford_product_import_history.type
     *
     * @mbggenerated
     */
    private Integer type;

    private String createUsername;
    private String stateDesp;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enford_product_import_history.id
     *
     * @return the value of enford_product_import_history.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enford_product_import_history.id
     *
     * @param id the value for enford_product_import_history.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enford_product_import_history.file_name
     *
     * @return the value of enford_product_import_history.file_name
     *
     * @mbggenerated
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enford_product_import_history.file_name
     *
     * @param fileName the value for enford_product_import_history.file_name
     *
     * @mbggenerated
     */
    public void setFileName(String fileName) {
        this.fileName = fileName == null ? null : fileName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enford_product_import_history.size
     *
     * @return the value of enford_product_import_history.size
     *
     * @mbggenerated
     */
    public String getSize() {
        return size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enford_product_import_history.size
     *
     * @param size the value for enford_product_import_history.size
     *
     * @mbggenerated
     */
    public void setSize(String size) {
        this.size = size == null ? null : size.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enford_product_import_history.create_by
     *
     * @return the value of enford_product_import_history.create_by
     *
     * @mbggenerated
     */
    public Integer getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enford_product_import_history.create_by
     *
     * @param createBy the value for enford_product_import_history.create_by
     *
     * @mbggenerated
     */
    public void setCreateBy(Integer createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enford_product_import_history.create_dt
     *
     * @return the value of enford_product_import_history.create_dt
     *
     * @mbggenerated
     */
    public Date getCreateDt() {
        return createDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enford_product_import_history.create_dt
     *
     * @param createDt the value for enford_product_import_history.create_dt
     *
     * @mbggenerated
     */
    public void setCreateDt(Date createDt) {
        this.createDt = createDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enford_product_import_history.state
     *
     * @return the value of enford_product_import_history.state
     *
     * @mbggenerated
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enford_product_import_history.state
     *
     * @param state the value for enford_product_import_history.state
     *
     * @mbggenerated
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enford_product_import_history.file_path
     *
     * @return the value of enford_product_import_history.file_path
     *
     * @mbggenerated
     */
    public String getFilePath() {
        return filePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enford_product_import_history.file_path
     *
     * @param filePath the value for enford_product_import_history.file_path
     *
     * @mbggenerated
     */
    public void setFilePath(String filePath) {
        this.filePath = filePath == null ? null : filePath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enford_product_import_history.file_type
     *
     * @return the value of enford_product_import_history.file_type
     *
     * @mbggenerated
     */
    public String getFileType() {
        return fileType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enford_product_import_history.file_type
     *
     * @param fileType the value for enford_product_import_history.file_type
     *
     * @mbggenerated
     */
    public void setFileType(String fileType) {
        this.fileType = fileType == null ? null : fileType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enford_product_import_history.type
     *
     * @return the value of enford_product_import_history.type
     *
     * @mbggenerated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enford_product_import_history.type
     *
     * @param type the value for enford_product_import_history.type
     *
     * @mbggenerated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    public void setCreateUsername(String createUsername) {
        this.createUsername = createUsername;
    }

    public String getCreateUsername() {
        return createUsername;
    }

    public void setStateDesp(String stateDesp) {
        this.stateDesp = stateDesp;
    }

    public String getStateDesp() {
        return stateDesp;
    }
}