package com.demo.model;

public class EnfordCustomProductKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enford_custom_product.custom_id
     *
     * @mbggenerated
     */
    private Integer customId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enford_custom_product.product_id
     *
     * @mbggenerated
     */
    private Integer productId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enford_custom_product.custom_id
     *
     * @return the value of enford_custom_product.custom_id
     *
     * @mbggenerated
     */
    public Integer getCustomId() {
        return customId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enford_custom_product.custom_id
     *
     * @param customId the value for enford_custom_product.custom_id
     *
     * @mbggenerated
     */
    public void setCustomId(Integer customId) {
        this.customId = customId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enford_custom_product.product_id
     *
     * @return the value of enford_custom_product.product_id
     *
     * @mbggenerated
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enford_custom_product.product_id
     *
     * @param productId the value for enford_custom_product.product_id
     *
     * @mbggenerated
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }
}