package com.demo.model;

import com.alibaba.fastjson.annotation.JSONField;

import java.util.Date;
import java.util.List;

public class EnfordProductCategory {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enford_product_category.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enford_product_category.code
     *
     * @mbggenerated
     */
    private Integer code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enford_product_category.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enford_product_category.parent
     *
     * @mbggenerated
     */
    private Integer parent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enford_product_category.create_dt
     *
     * @mbggenerated
     */
    @JSONField(format="yyyy-MM-dd HH:mm:ss")
    private Date createDt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enford_product_category.update_dt
     *
     * @mbggenerated
     */
    @JSONField(format="yyyy-MM-dd HH:mm:ss")
    private Date updateDt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enford_product_category.create_by
     *
     * @mbggenerated
     */
    private Integer createBy;

    private String createUsername;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enford_product_category.update_by
     *
     * @mbggenerated
     */
    private Integer updateBy;

    private String imgUrl;

    /**
     * 该品类下的完成市调的百分比
     */
    private Integer haveFinished;

    /**
     * 该品类下的商品总数
     */
    private Integer codCount;

    private List<EnfordProductCommodity> commodityList;

    private Integer finishCount;

    private Integer codCountByYear;

    private String finishCountByMonth;

    private String finishCountByYear;

    private String parentCode;

    private String parentName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enford_product_category.id
     *
     * @return the value of enford_product_category.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enford_product_category.id
     *
     * @param id the value for enford_product_category.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enford_product_category.code
     *
     * @return the value of enford_product_category.code
     *
     * @mbggenerated
     */
    public Integer getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enford_product_category.code
     *
     * @param code the value for enford_product_category.code
     *
     * @mbggenerated
     */
    public void setCode(Integer code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enford_product_category.name
     *
     * @return the value of enford_product_category.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enford_product_category.name
     *
     * @param name the value for enford_product_category.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enford_product_category.parent
     *
     * @return the value of enford_product_category.parent
     *
     * @mbggenerated
     */
    public Integer getParent() {
        return parent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enford_product_category.parent
     *
     * @param parent the value for enford_product_category.parent
     *
     * @mbggenerated
     */
    public void setParent(Integer parent) {
        this.parent = parent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enford_product_category.create_dt
     *
     * @return the value of enford_product_category.create_dt
     *
     * @mbggenerated
     */
    public Date getCreateDt() {
        return createDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enford_product_category.create_dt
     *
     * @param createDt the value for enford_product_category.create_dt
     *
     * @mbggenerated
     */
    public void setCreateDt(Date createDt) {
        this.createDt = createDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enford_product_category.update_dt
     *
     * @return the value of enford_product_category.update_dt
     *
     * @mbggenerated
     */
    public Date getUpdateDt() {
        return updateDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enford_product_category.update_dt
     *
     * @param updateDt the value for enford_product_category.update_dt
     *
     * @mbggenerated
     */
    public void setUpdateDt(Date updateDt) {
        this.updateDt = updateDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enford_product_category.create_by
     *
     * @return the value of enford_product_category.create_by
     *
     * @mbggenerated
     */
    public Integer getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enford_product_category.create_by
     *
     * @param createBy the value for enford_product_category.create_by
     *
     * @mbggenerated
     */
    public void setCreateBy(Integer createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enford_product_category.update_by
     *
     * @return the value of enford_product_category.update_by
     *
     * @mbggenerated
     */
    public Integer getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enford_product_category.update_by
     *
     * @param updateBy the value for enford_product_category.update_by
     *
     * @mbggenerated
     */
    public void setUpdateBy(Integer updateBy) {
        this.updateBy = updateBy;
    }

    public String getCreateUsername() {
        return createUsername;
    }

    public void setCreateUsername(String createUsername) {
        this.createUsername = createUsername;
    }

    public String getImgUrl() {
        return imgUrl;
    }

    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl;
    }

    public Integer getHaveFinished() {
        return haveFinished;
    }

    public void setHaveFinished(Integer haveFinished) {
        this.haveFinished = haveFinished;
    }

    public Integer getCodCount() {
        return codCount;
    }

    public void setCodCount(Integer codCount) {
        this.codCount = codCount;
    }

    public List<EnfordProductCommodity> getCommodityList() {
        return commodityList;
    }

    public void setCommodityList(List<EnfordProductCommodity> commodityList) {
        this.commodityList = commodityList;
    }

    public Integer getFinishCount() {
        return finishCount;
    }

    public void setFinishCount(Integer finishCount) {
        this.finishCount = finishCount;
    }

    public Integer getCodCountByYear() {
        return codCountByYear;
    }

    public void setCodCountByYear(Integer codCountByYear) {
        this.codCountByYear = codCountByYear;
    }

    public String getParentCode() {
        return parentCode;
    }

    public void setParentCode(String parentCode) {
        this.parentCode = parentCode;
    }

    public String getParentName() {
        return parentName;
    }

    public void setParentName(String parentName) {
        this.parentName = parentName;
    }

    public String getFinishCountByMonth() {
        return finishCountByMonth;
    }

    public void setFinishCountByMonth(String finishCountByMonth) {
        this.finishCountByMonth = finishCountByMonth;
    }

    public String getFinishCountByYear() {
        return finishCountByYear;
    }

    public void setFinishCountByYear(String finishCountByYear) {
        this.finishCountByYear = finishCountByYear;
    }
}