package com.demo.model;

import java.util.Date;

public class EnfordSyncLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enford_sync_log.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enford_sync_log.res_id
     *
     * @mbggenerated
     */
    private Integer resId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enford_sync_log.bill_number
     *
     * @mbggenerated
     */
    private String billNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enford_sync_log.before_state
     *
     * @mbggenerated
     */
    private Integer beforeState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enford_sync_log.before_confirm_type
     *
     * @mbggenerated
     */
    private Integer beforeConfirmType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enford_sync_log.after_state
     *
     * @mbggenerated
     */
    private Integer afterState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enford_sync_log.after_confirm_type
     *
     * @mbggenerated
     */
    private Integer afterConfirmType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enford_sync_log.sync_dt
     *
     * @mbggenerated
     */
    private Date syncDt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enford_sync_log.sync_result
     *
     * @mbggenerated
     */
    private Integer syncResult;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enford_sync_log.has_price
     *
     * @mbggenerated
     */
    private Integer hasPrice;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enford_sync_log.id
     *
     * @return the value of enford_sync_log.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enford_sync_log.id
     *
     * @param id the value for enford_sync_log.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enford_sync_log.res_id
     *
     * @return the value of enford_sync_log.res_id
     *
     * @mbggenerated
     */
    public Integer getResId() {
        return resId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enford_sync_log.res_id
     *
     * @param resId the value for enford_sync_log.res_id
     *
     * @mbggenerated
     */
    public void setResId(Integer resId) {
        this.resId = resId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enford_sync_log.bill_number
     *
     * @return the value of enford_sync_log.bill_number
     *
     * @mbggenerated
     */
    public String getBillNumber() {
        return billNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enford_sync_log.bill_number
     *
     * @param billNumber the value for enford_sync_log.bill_number
     *
     * @mbggenerated
     */
    public void setBillNumber(String billNumber) {
        this.billNumber = billNumber == null ? null : billNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enford_sync_log.before_state
     *
     * @return the value of enford_sync_log.before_state
     *
     * @mbggenerated
     */
    public Integer getBeforeState() {
        return beforeState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enford_sync_log.before_state
     *
     * @param beforeState the value for enford_sync_log.before_state
     *
     * @mbggenerated
     */
    public void setBeforeState(Integer beforeState) {
        this.beforeState = beforeState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enford_sync_log.before_confirm_type
     *
     * @return the value of enford_sync_log.before_confirm_type
     *
     * @mbggenerated
     */
    public Integer getBeforeConfirmType() {
        return beforeConfirmType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enford_sync_log.before_confirm_type
     *
     * @param beforeConfirmType the value for enford_sync_log.before_confirm_type
     *
     * @mbggenerated
     */
    public void setBeforeConfirmType(Integer beforeConfirmType) {
        this.beforeConfirmType = beforeConfirmType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enford_sync_log.after_state
     *
     * @return the value of enford_sync_log.after_state
     *
     * @mbggenerated
     */
    public Integer getAfterState() {
        return afterState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enford_sync_log.after_state
     *
     * @param afterState the value for enford_sync_log.after_state
     *
     * @mbggenerated
     */
    public void setAfterState(Integer afterState) {
        this.afterState = afterState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enford_sync_log.after_confirm_type
     *
     * @return the value of enford_sync_log.after_confirm_type
     *
     * @mbggenerated
     */
    public Integer getAfterConfirmType() {
        return afterConfirmType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enford_sync_log.after_confirm_type
     *
     * @param afterConfirmType the value for enford_sync_log.after_confirm_type
     *
     * @mbggenerated
     */
    public void setAfterConfirmType(Integer afterConfirmType) {
        this.afterConfirmType = afterConfirmType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enford_sync_log.sync_dt
     *
     * @return the value of enford_sync_log.sync_dt
     *
     * @mbggenerated
     */
    public Date getSyncDt() {
        return syncDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enford_sync_log.sync_dt
     *
     * @param syncDt the value for enford_sync_log.sync_dt
     *
     * @mbggenerated
     */
    public void setSyncDt(Date syncDt) {
        this.syncDt = syncDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enford_sync_log.sync_result
     *
     * @return the value of enford_sync_log.sync_result
     *
     * @mbggenerated
     */
    public Integer getSyncResult() {
        return syncResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enford_sync_log.sync_result
     *
     * @param syncResult the value for enford_sync_log.sync_result
     *
     * @mbggenerated
     */
    public void setSyncResult(Integer syncResult) {
        this.syncResult = syncResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enford_sync_log.has_price
     *
     * @return the value of enford_sync_log.has_price
     *
     * @mbggenerated
     */
    public Integer getHasPrice() {
        return hasPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enford_sync_log.has_price
     *
     * @param hasPrice the value for enford_sync_log.has_price
     *
     * @mbggenerated
     */
    public void setHasPrice(Integer hasPrice) {
        this.hasPrice = hasPrice;
    }
}