package com.demo.model;

public class EnfordMarketResearchDeptKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enford_market_research_dept.res_id
     *
     * @mbggenerated
     */
    private Integer resId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enford_market_research_dept.exe_id
     *
     * @mbggenerated
     */
    private Integer exeId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enford_market_research_dept.res_id
     *
     * @return the value of enford_market_research_dept.res_id
     *
     * @mbggenerated
     */
    public Integer getResId() {
        return resId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enford_market_research_dept.res_id
     *
     * @param resId the value for enford_market_research_dept.res_id
     *
     * @mbggenerated
     */
    public void setResId(Integer resId) {
        this.resId = resId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enford_market_research_dept.exe_id
     *
     * @return the value of enford_market_research_dept.exe_id
     *
     * @mbggenerated
     */
    public Integer getExeId() {
        return exeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enford_market_research_dept.exe_id
     *
     * @param exeId the value for enford_market_research_dept.exe_id
     *
     * @mbggenerated
     */
    public void setExeId(Integer exeId) {
        this.exeId = exeId;
    }
}