package com.demo.model;

public class EnfordMarketResearchCommodity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enford_market_research_commodity.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enford_market_research_commodity.res_id
     *
     * @mbggenerated
     */
    private Integer resId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enford_market_research_commodity.cod_id
     *
     * @mbggenerated
     */
    private Integer codId;

    private String resName;

    private String codName;

    private String codSize;

    private String codUnit;

    private String codBarCode;

    private String codCategory;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enford_market_research_commodity.id
     *
     * @return the value of enford_market_research_commodity.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enford_market_research_commodity.id
     *
     * @param id the value for enford_market_research_commodity.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enford_market_research_commodity.res_id
     *
     * @return the value of enford_market_research_commodity.res_id
     *
     * @mbggenerated
     */
    public Integer getResId() {
        return resId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enford_market_research_commodity.res_id
     *
     * @param resId the value for enford_market_research_commodity.res_id
     *
     * @mbggenerated
     */
    public void setResId(Integer resId) {
        this.resId = resId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enford_market_research_commodity.cod_id
     *
     * @return the value of enford_market_research_commodity.cod_id
     *
     * @mbggenerated
     */
    public Integer getCodId() {
        return codId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enford_market_research_commodity.cod_id
     *
     * @param codId the value for enford_market_research_commodity.cod_id
     *
     * @mbggenerated
     */
    public void setCodId(Integer codId) {
        this.codId = codId;
    }

    public String getResName() {
        return resName;
    }

    public void setResName(String resName) {
        this.resName = resName;
    }

    public String getCodName() {
        return codName;
    }

    public void setCodName(String codName) {
        this.codName = codName;
    }

    public String getCodSize() {
        return codSize;
    }

    public void setCodSize(String codSize) {
        this.codSize = codSize;
    }

    public String getCodUnit() {
        return codUnit;
    }

    public void setCodUnit(String codUnit) {
        this.codUnit = codUnit;
    }

    public String getCodBarCode() {
        return codBarCode;
    }

    public void setCodBarCode(String codBarCode) {
        this.codBarCode = codBarCode;
    }

    public String getCodCategory() {
        return codCategory;
    }

    public void setCodCategory(String codCategory) {
        this.codCategory = codCategory;
    }
}