package com.demo.model;

import java.util.Date;

public class EnfordProductPrice {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enford_product_price.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enford_product_price.purchase_price
     *
     * @mbggenerated
     */
    private Float purchasePrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enford_product_price.retail_price
     *
     * @mbggenerated
     */
    private Float retailPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enford_product_price.create_dt
     *
     * @mbggenerated
     */
    private Date createDt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enford_product_price.update_dt
     *
     * @mbggenerated
     */
    private Date updateDt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enford_product_price.com_id
     *
     * @mbggenerated
     */
    private Integer comId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enford_product_price.org_id
     *
     * @mbggenerated
     */
    private Integer orgId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enford_product_price.create_by
     *
     * @mbggenerated
     */
    private Integer createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enford_product_price.update_by
     *
     * @mbggenerated
     */
    private Integer updateBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enford_product_price.miss
     *
     * @mbggenerated
     */
    private Integer miss;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enford_product_price.id
     *
     * @return the value of enford_product_price.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enford_product_price.id
     *
     * @param id the value for enford_product_price.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enford_product_price.purchase_price
     *
     * @return the value of enford_product_price.purchase_price
     *
     * @mbggenerated
     */
    public Float getPurchasePrice() {
        return purchasePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enford_product_price.purchase_price
     *
     * @param purchasePrice the value for enford_product_price.purchase_price
     *
     * @mbggenerated
     */
    public void setPurchasePrice(Float purchasePrice) {
        this.purchasePrice = purchasePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enford_product_price.retail_price
     *
     * @return the value of enford_product_price.retail_price
     *
     * @mbggenerated
     */
    public Float getRetailPrice() {
        return retailPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enford_product_price.retail_price
     *
     * @param retailPrice the value for enford_product_price.retail_price
     *
     * @mbggenerated
     */
    public void setRetailPrice(Float retailPrice) {
        this.retailPrice = retailPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enford_product_price.create_dt
     *
     * @return the value of enford_product_price.create_dt
     *
     * @mbggenerated
     */
    public Date getCreateDt() {
        return createDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enford_product_price.create_dt
     *
     * @param createDt the value for enford_product_price.create_dt
     *
     * @mbggenerated
     */
    public void setCreateDt(Date createDt) {
        this.createDt = createDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enford_product_price.update_dt
     *
     * @return the value of enford_product_price.update_dt
     *
     * @mbggenerated
     */
    public Date getUpdateDt() {
        return updateDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enford_product_price.update_dt
     *
     * @param updateDt the value for enford_product_price.update_dt
     *
     * @mbggenerated
     */
    public void setUpdateDt(Date updateDt) {
        this.updateDt = updateDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enford_product_price.com_id
     *
     * @return the value of enford_product_price.com_id
     *
     * @mbggenerated
     */
    public Integer getComId() {
        return comId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enford_product_price.com_id
     *
     * @param comId the value for enford_product_price.com_id
     *
     * @mbggenerated
     */
    public void setComId(Integer comId) {
        this.comId = comId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enford_product_price.org_id
     *
     * @return the value of enford_product_price.org_id
     *
     * @mbggenerated
     */
    public Integer getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enford_product_price.org_id
     *
     * @param orgId the value for enford_product_price.org_id
     *
     * @mbggenerated
     */
    public void setOrgId(Integer orgId) {
        this.orgId = orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enford_product_price.create_by
     *
     * @return the value of enford_product_price.create_by
     *
     * @mbggenerated
     */
    public Integer getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enford_product_price.create_by
     *
     * @param createBy the value for enford_product_price.create_by
     *
     * @mbggenerated
     */
    public void setCreateBy(Integer createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enford_product_price.update_by
     *
     * @return the value of enford_product_price.update_by
     *
     * @mbggenerated
     */
    public Integer getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enford_product_price.update_by
     *
     * @param updateBy the value for enford_product_price.update_by
     *
     * @mbggenerated
     */
    public void setUpdateBy(Integer updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enford_product_price.miss
     *
     * @return the value of enford_product_price.miss
     *
     * @mbggenerated
     */
    public Integer getMiss() {
        return miss;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enford_product_price.miss
     *
     * @param miss the value for enford_product_price.miss
     *
     * @mbggenerated
     */
    public void setMiss(Integer miss) {
        this.miss = miss;
    }
}