package com.demo.model;

import java.util.Date;

public class EnfordCustomProduct extends EnfordCustomProductKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enford_custom_product.secret_key
     *
     * @mbggenerated
     */
    private String secretKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enford_custom_product.start_date
     *
     * @mbggenerated
     */
    private Date startDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enford_custom_product.end_date
     *
     * @mbggenerated
     */
    private Date endDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enford_custom_product.code
     *
     * @mbggenerated
     */
    private String code;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enford_custom_product.secret_key
     *
     * @return the value of enford_custom_product.secret_key
     *
     * @mbggenerated
     */
    public String getSecretKey() {
        return secretKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enford_custom_product.secret_key
     *
     * @param secretKey the value for enford_custom_product.secret_key
     *
     * @mbggenerated
     */
    public void setSecretKey(String secretKey) {
        this.secretKey = secretKey == null ? null : secretKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enford_custom_product.start_date
     *
     * @return the value of enford_custom_product.start_date
     *
     * @mbggenerated
     */
    public Date getStartDate() {
        return startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enford_custom_product.start_date
     *
     * @param startDate the value for enford_custom_product.start_date
     *
     * @mbggenerated
     */
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enford_custom_product.end_date
     *
     * @return the value of enford_custom_product.end_date
     *
     * @mbggenerated
     */
    public Date getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enford_custom_product.end_date
     *
     * @param endDate the value for enford_custom_product.end_date
     *
     * @mbggenerated
     */
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enford_custom_product.code
     *
     * @return the value of enford_custom_product.code
     *
     * @mbggenerated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enford_custom_product.code
     *
     * @param code the value for enford_custom_product.code
     *
     * @mbggenerated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }
}